name: ftcon24usa_workshop
description: FlutterCon 2024 USA workshop
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  cached_network_image: 3.4.1
  dartx: 1.2.0
  dio: 5.7.0
  flutter:
    sdk: flutter
  freezed_annotation: 2.4.4
  intl: 0.19.0
  json_annotation: 4.9.0
  retrofit: 4.4.1
  url_launcher: 6.3.0

dev_dependencies:
  build_runner: 2.4.12
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0
  freezed: 2.5.7
  json_serializable: 6.8.0
  retrofit_generator: 9.1.2

flutter:
  uses-material-design: true
